const EMAILREGEX = "^\\S+@\\S+\\.\\S+$"
const MAXSCREEN = 1280
const MEDIUMSCREEN = 1024
const SMALLSCREEN = 650
const INITMOREMAXSCREEN = 16
const INITLESSMAXSCREEN = 12
const INITMEDIUMSCREEN = 8
const INITSMALLSCREEN = 5
const STEPMAXSCREEN = 4
const STEPMEDIUMSCREEN = 3
const STEPSMALLSCREEN = 2
export {
  EMAILREGEX,
  MAXSCREEN,
  MEDIUMSCREEN,
  SMALLSCREEN,
  INITMOREMAXSCREEN,
  INITLESSMAXSCREEN,
  INITMEDIUMSCREEN,
  INITSMALLSCREEN,
  STEPMAXSCREEN,
  STEPMEDIUMSCREEN,
  STEPSMALLSCREEN
}